"""
state.py
--------
Defines the LangGraph agent state and all Pydantic structured output models.

Two categories of classes here:
  1. Pydantic BaseModels  → used as structured output schemas for LLM nodes
  2. FAQAgentState        → the TypedDict that flows through the LangGraph graph
"""

from typing import TypedDict, List, Optional
from pydantic import BaseModel, Field


# ─────────────────────────────────────────────
# Pydantic Structured Output Models
# ─────────────────────────────────────────────

class GeneratedAnswer(BaseModel):
    """
    Structured output schema for the Generator node (Gemini).
    Forces the LLM to always return a clean answer field.
    """
    answer: str = Field(
        description=(
            "A comprehensive, accurate, and well-explained answer to the FAQ question. "
            "Must be at least 60 words and technically correct."
        )
    )


class ValidationOutput(BaseModel):
    """
    Structured output schema for the Validator node (Groq).
    Forces the LLM to return a boolean verdict + justification.
    """
    is_valid: bool = Field(
        description=(
            "True if the answer is accurate, complete, clear, and at least 50 words. "
            "False if it is vague, incorrect, too short, or off-topic."
        )
    )
    remarks: str = Field(
        description=(
            "A brief explanation of why the answer is valid or invalid. "
            "If invalid, include what specific improvement is needed."
        )
    )


# ─────────────────────────────────────────────
# LangGraph Agent State
# ─────────────────────────────────────────────

class FAQAgentState(TypedDict):
    """
    The central state object that flows through every node of the graph.

    Fields:
        questions        → full list of input FAQ dicts loaded from input.json
        current_index    → index of the question currently being processed
        current_question → dict of the active FAQ item {"faqQuestion": int, "Question": str}
        current_answer   → the latest answer string generated by Gemini
        is_valid         → boolean from Groq validator (True = answer accepted)
        remarks          → validator's explanation for the verdict
        iteration_count  → how many generate→validate cycles have run for this question
        results          → accumulated list of final result dicts (one per question)
    """
    questions: List[dict]
    current_index: int
    current_question: dict
    current_answer: str
    is_valid: bool
    remarks: str
    iteration_count: int
    results: List[dict]